### PR TITLE
add jackum to the team list

### PR DESCRIPTION
**Pull request by JMurphyWeb**
I definitely need a new photo!! SMILE

### CODE REVIEW

**Comment by JMurphyWeb** [comment]
@nelsonic sure thing.

**Comment by JMurphyWeb** [comment]
@nelsonic done but for some reason I cannot add labels to issues in the dwyl repos.

**Comment by JMurphyWeb** [comment]
@nelsonic I wanted to see if there was anything else that needs to be done for this PR?

**Comment by nelsonic** [comment]
@JMurphyWeb _approved_ from my end. 
_Ideally_ we should have `standard` photos https://github.com/dwyl/hq/issues/150 `forEach` person `before` they are added to the `members.json` because nobody will _retrospectively_ update their profile photo ...

**Pull request merged**
