### PR TITLE
First draft

### PR DESCRIPTION
**Pull request by hdrdavies**
Question: we moved the index.html into a ```views/``` folder. How do you compare the diff between moved files? 

# Ready to merge!

### CODE REVIEW

**Comment by nelsonic** [comment]
@hdrdavies please don't worry about comparing a "*diff*" between the old site and the new.
Our objective with this re-design is to get something *betterer* than the crappy one-pager we put up in our pre-websummit hackathon... pretty sure that with your input it will be an order of magnitude *betterer* so we aren't going to spend *that* much time "*git diffing*" ... the proof will be from a *user*-perspective not a coder one. :+1:

**Comment by iteles** [comment]
@hdrdavies Is this a `[WiP]` PR as we discussed? :blush:

**Comment by iteles** [comment]
@hdrdavies Agree completely with @nelsonic. As I mentioned, I'm not married to _anything_ on that crappy first iteration, even the colour scheme (apart from pops of teal because that's our brand colour). Throw it away and start from scratch!

**Comment by mantagen** [comment]
@hdrdavies @iteles @nelsonic 
We've stuck with the pure css, just for their grid system - which I'm not sure it's the best (although they do have fifths, which many grid systems don't have!) - so maybe we'll spend an hour switching at some point. However, haven't properly looked to see what other bloat is in the pure css framework which we're not even using!

Latest commits have created "our values" page. We are pretty much happy with it.
Also created "meet the team" page. I think we are having a little difficulty finding an awesome example of this which looks professionally designed etc. What you do you guys think @iteles @nelsonic ? Seen any fab examples of this? I know Liberty-X's team page got a mention before, and it's nice - however we struggled going from that to something which was genuinely *beautiful*

Inspiration appreciated.

**Comment by mantagen** [comment]
1. Changed contact anchor link in navbar, making it relative to root, so that it works from all pages.
2. Edited and new 'process' diagram, to fit with the current aestheic #61.
3. Added and styled content to 'process' section #100.
4. Edited and added images and styled 'offering' section #86.

Generally all looks fine. However there is still an issue with some vertical centering and some margining. Will create an issue.

**Comment by hdrdavies** [comment]
Based on stand-up on Weds afternoon, going to comment out 'What our clients say' and 'Meet the team Page' for now due to lack of content, to prepare a PR

**Comment by hdrdavies** [comment]
Done! Ready for merge :+1:

**Comment by hdrdavies** [comment]
Done! Ready to merge!

**Comment by iteles** [comment]
@nelsonic Would appreciate comments from you here too :+1:

**Comment by nelsonic** [comment]
Created a test instance on heroku with this branch: https://dwylio-test.herokuapp.com

**Comment by iteles** [comment]
Firstly, thanks for all your hard work on this, we genuinely appreciate it!
Apologies also for not giving you guys more constant feedback on this, that's my bad.

Some very honest notes on this:
+ I can't handle all the grey. The homepage just looks _dull_ to me at the moment and it's all about that first impression: https://github.com/dwyl/dwyl.github.io/issues/93#issuecomment-182618709
+ That tagline. It still doesn't make any sense; we can't deploy with that. 
https://github.com/dwyl/dwyl.github.io/issues/108#issuecomment-182406494 #112 
+ On the splash, the links at the bottom don't look like links - there's nothing to draw people to click on them and I'm not entirely sure splitting people's attention with 2 navigation areas works, we need to test this
+ Also on nav: https://github.com/dwyl/dwyl.github.io/issues/115
+ https://github.com/dwyl/dwyl.github.io/issues/86#issuecomment-182628482 + https://github.com/dwyl/dwyl.github.io/issues/86#issuecomment-182629950 which are actually copy problems and on me to resolve
+ https://github.com/dwyl/dwyl.github.io/issues/100#issuecomment-182630439 + https://github.com/dwyl/dwyl.github.io/issues/100#issuecomment-182630826
+ Really like that you've adapted the diagram to fit the style but a job for me here to re-write the copy
+ https://github.com/dwyl/dwyl.github.io/issues/55#issuecomment-182632971
+ On the contact form alignment: https://github.com/dwyl/dwyl.github.io/issues/116
+ And on the contact form placeholder text - absolutely not facebook (see https://github.com/dwyl/start-here/blame/master/manifesto.md#L22) :weary: : https://github.com/dwyl/dwyl.github.io/issues/55#issuecomment-182632971
+ I also want to say that the rounded corners are too rounded and makes the whole thing look cartoony (in offering and values) but think that may put me a step too close to the 'impossible to please client' zone :grin:

**Comment by hdrdavies** [comment]
above commit is me on my brother's mac... :grimacing:

**Comment by iteles** [comment]
@hdrdavies Where are we with being able to deploy to production?

**Comment by hdrdavies** [comment]
Only things that aren't complete yet are #120 #126 #128 & the team page.

**Comment by iteles** [comment]
Sounds like we can pull this together in time then. Tomorrow we should aim to follow the priorities assigned to items more closely.

**Comment by nelsonic** [comment]
@hdrdavies, @mantagen & @iteles can we *publish* this version for today's talk at TechHub...?

**Comment by hdrdavies** [comment]
@nelsonic Quite possibly- if the content is ok. Just don't open it on firefox!

**Comment by mantagen** [comment]
@hdrdavies @nelsonic @iteles 
I just made a quick fix to navbar on firefox in branch firefoxNavQuickFix , in case we want to go live with this before evening's event - as both @hdrdavies  and I have interview this afternoon.

**Comment by nelsonic** [comment]
@mantagen thanks for the update did you PR it?

**Comment by mantagen** [comment]
@nelsonic I have done now!

**Comment by nelsonic** [comment]
@mantagen's FireFox Fix has been merged. :white_check_mark: 
@iteles please check what else is *required* before we can publish the new version. :mag: (*thanks*)

**Comment by iteles** [comment]
Anything labelled 'priority-2' 😊

**Comment by hdrdavies** [comment]
Done and ready to merge when happy :+1: @nelsonic @iteles

**Comment by hdrdavies** [comment]
Above fixes address problems :+1:

**Comment by hdrdavies** [comment]
hasn't deployed latest commit but the tagline looks better: 

screen shot 2016-02-18 at 12 12 25

**Pull request merged**
