### PR TITLE
keep the default behavior of the form for a better web

### PR DESCRIPTION
**Pull request by yuanchuan**
Now it can do some basic form validations and be submitted by the Enter key.

### CODE REVIEW

**Comment by enociz** [comment]
❤️ your effort!

But, something seems fishy - there have been changes to the files since your request. I reckon this is a job for @iteles or @nelsonic to deal with (ping!).

**Comment by iteles** [comment]
@yuanchuan My apologies, I'm not sure how I missed this one! Thank you for this _great_ contribution and my apologies it took us a while to find it! :disappointed: 

The merge conflicts here are small (mostly in the `<head>` tag I think) and I would love for you to get credit for this piece of work! Would you mind merging with `master` on your end and resolving the conflicts?

I'll merge as soon as it's ready :blush:

Thank you and our apologies again!

_P.S. Thanks for spotting this @enociz_ :+1:

**Comment by yuanchuan** [comment]
Oh never mind.
I will make an update to the PR soon :D

**Comment by iteles** [comment]
Thanks @yuanchuan :blush: :+1:

**Pull request merged**
