### PR TITLE
Adding myself, Natalia, to members.json

### PR DESCRIPTION
**Pull request by NataliaLKB**
This should complete __step 3__ listed in the description here https://github.com/dwyl/hq/issues/147

I realise that this picture isn't following the ideal [picture guidelines](https://github.com/dwyl/hq/issues/150), but hopefully this will be an okay first go.

Also, my description might need suggestions. @iteles has suggested "Technical Advisor" but I don't know if I can say that before I advise on anything 😉

### CODE REVIEW

**Comment by NataliaLKB** [comment]
Thanks @nelsonic! I forgot to put a screenshot of my change in the description. Whoops 😱 .

Here it is (better late than never? )

**Comment by NataliaLKB** [comment]
Also, totally love this:

**Comment by nelsonic** [comment]
@NataliaLKB, [I hope you _don't mind_](https://youtu.be/mBCVEcjScTQ?t=28s) that I "_fixed_" the merge conflict with a _tiny_ "_upgrade_" to your status. 😮  

(_the beauty of version control being that anyone can see that **you** `did not` **personally** "inflate" or "[uptitle](http://www.thefreedictionary.com/uptitling)" your "position" ... given how modest you are, that would `never` happen (that's a good thing!)... but rather someone `else` elevated you to the "status" you deserve... you have [advised us on numerous occasions informally](https://github.com/dwyl/learn-react/issues/6#issuecomment-165412314), and we **hope** some day you will [**lead** us](https://youtu.be/ReRcHdeUG9Y) because we **see** your potential... you "**get** it" (people, society & technology!) the way I (nelson) [quite clearly do not](https://twitter.com/msmichellegar/status/811880381381300225) (**yet...!**) and I want to (keep) learn(ing) with/from you...!_) 😜  🦄  🎉  ❤️  ✅ 

_Anyway_... thanks for the PR! hope you have a _fantastic day_! 🚀 

Hope we can organise another [meal](https://github.com/dwyl/hq/issues/121#issuecomment-265997961) soon... Let us know if you have any pref for dishes...! 🍴 😋

**Comment by iteles** [comment]
Also, I'm a little late to this party, but @NataliaLKB I remember a *lot* of technical advice being given by you to dwyl teams during #dwylsummer and F&C students who have gone on to become some of dwyl's best developers! So I would suggest you've advised on *plenty* 👍 :tada:

**Comment by markwilliamfirth** [comment]
@nelsonic can we update to "Alumni" to "Alumnus"?

**Comment by nelsonic** [comment]
@markwilliamfirth I don't know the difference so, yes. (_cause you know more engrish than me..._) 👍

**Comment by markwilliamfirth** [comment]
😱 😱 😱 😱 😱 😱 😱 😱 

I stand corrected - **alumna**

**Pull request merged**
