### PR TITLE
fixed anchor div positioning

### PR DESCRIPTION
**Pull request by mantagen**
Wasn't sure if 'anchor' was a class name consistent with the style guide. Let me know if not :)

### CODE REVIEW

**Comment by iteles** [comment]
@mantagen Ah, I see the confusion, I really didn't explain that very well in #63 !
I was referring to anchors as in [HTML anchors](http://www.w3.org/TR/html401/struct/links.html).

I couldn't get the anchoring (as in HTML anchoring to an #id) to work _at all_ so to make it even _mildly_ functional (i.e. Skip down to the _vicinity_ of where I needed it to be), I had to insert **temporary divs** further up in the code than they should be :flushed: :see_no_evil: *hangs head in shame*

For example (you just need to search for the word 'TEMPORARY' throughout to find them):
https://github.com/dwyl/dwyl.github.io/blob/18ef9fa862d08f2c4554e2e486255bd7f8f5647d/index.html#L88

The example above on line 88 shouldn't be a separate div at all, it should be an id on https://github.com/dwyl/dwyl.github.io/blob/18ef9fa862d08f2c4554e2e486255bd7f8f5647d/index.html#L87

Does that make sense?

**Comment by hdrdavies** [comment]
@iteles after testing locally @mantagen's code seems to work great! Ready for a merge!

**Comment by iteles** [comment]
@mantagen @hdrdavies Wonderful, thanks!

**Comment by nelsonic** [comment]
@iteles thanks for merging in this fix. :wrench: 
sadly, the Nav Links are still commented out due to my previous commit... 
see: https://github.com/dwyl/dwyl.github.io/blob/a1c974e1a2b992b80b8803e8dfd4187edcfd9de3/index.html#L69
So we need to *uncomment* that for this to work...

**Comment by iteles** [comment]
Agreed, hence #90 :wink:

**Comment by nelsonic** [comment]
Thanks. :+1:

**Pull request merged**
