### PR TITLE
Sets up welcome page

### PR DESCRIPTION
**Pull request by iteles**
Fixes some minor CSS issue in main.css but mostly adds a proposed variation `/welcome.html` with an 'Our Story' section for A/B testing.

The whole variation is in separate files (`welcome.html` and `welcome.css`) so won't affect the main site for now apart from fixing a little CSS.

@nelsonic The text in the variation most likely needs revising.

### CODE REVIEW

**Comment by nelsonic** [comment]
is this still "WIP" or have you assigned it to me for review/merge? :question:

**Comment by iteles** [comment]
I only assign something when it's ready to be reviewed/discussed and eventually merged.

Please review if you can, not a huge rush and I'm happy to talk you through the highlights to speed up the process. Just let me know.

**Comment by nelsonic** [comment]
*Right*... but, leaving the word "WIP" as the only description for the PR *suggests* it's not "*ready*"...

**Comment by iteles** [comment]
@nelsonic Must not have updated on your end, apologies.

I always update the description fully before assigning/asking for a review. Should look like this:
screen shot 2015-10-30 at 14 42 59

**Comment by nelsonic** [comment]
Merging to show evo in project history. but we do need a #51

**Pull request merged**
