### PR TITLE
WebSummit

### PR DESCRIPTION
**Pull request by nelsonic**
## Website Re-Write

+ adds detail to readme on why we are migrating away from using GitHub Pages to adoro ... custom urls!
+ Complete Overhaul: https://github.com/dwyl/dwyl.github.io/issues/51
  + Converts site to PureCSS #57 
  + Sorts out bug #59 
+ Implements question-based navigation: https://github.com/dwyl/dwyl.github.io/issues/54
+ Adds new content for 'What' and 'How'
+ Changes 'Beliefs' section content to match _hiring a team vs building time_
+ Adds new Contact form Using Google Spreadsheet. Fixes signup issue: https://github.com/dwyl/dwyl.github.io/issues/67

### CODE REVIEW

**Comment by iteles** [comment]
**REMEMBER:** `old-files` directory has been created during dev for _ease of reference_. This directory **should be deleted** before merging with `master`.

**Comment by iteles** [comment]
@nelsonic The very first iteration (bare bones, will look different by tonight), is here at the moment.

There are still issues on certain devices like the Nexus 5 but this is very temporary until we fix #51 in the next 24 hours.

screen shot 2015-11-02 at 12 59 02

**Comment by iteles** [comment]
At this point, we have moved the original (really not great) content to the new template and started making some small changes to copy (navigation links) and moving the beta tester sign up link (provisionally) to the bottom of the page.

**Comment by iteles** [comment]
@nelsonic 
**Most important things for this morning:**
+ https://github.com/dwyl/dwyl.github.io/issues/52
+ Review website in general
+ Review new content in 'What do we believe in?' section (I think we need to add to this with _at least_ `continuous learning`, `standards`, `metric driven` and another `s` but I'm too tired for my brain to function enough to write that copy right now)

**Comment by iteles** [comment]
@nelsonic I've made some additional (tiny) changes - fixing the title and the broken instagram link - which will need to be pushed to heroku, but in general, I think it might be time to merge this with master.

Do you have any objections? (I ask because there are a few commits of mine here which you've been reviewing along the way)

**Comment by iteles** [comment]
My greens are looking awfully non-dark :wink:

**Comment by nelsonic** [comment]
@iteles please `git pull` and review the changes I made. then merge at will. thanks.

**Comment by nelsonic** [comment]
Paying for a Heroku Dyno to improve initial page load.
dwyl io-heroku-dyno

This will be *resolved* when we enable CloudFlare: https://github.com/dwyl/adoro/issues/20

**Comment by iteles** [comment]
👍🏻 I'm going to take that as meaning that you're comfortable with _my_ commits. I'll pull and review now, thanks!

**Comment by nelsonic** [comment]
We need to get this *merged* and then iterate further.

**Pull request merged**
