### PR TITLE
Add Rob to the members list

### PR DESCRIPTION
**Pull request by RobStallion**

### CODE REVIEW

**Comment by RobStallion** [comment]
@nelsonic New and improved branch name.

@iteles New and improved photo (hope this one is ok)

**Comment by iteles** [comment]
@RobStallion I merged in @JMurphyWeb's one first so you have a small conflict to resolve, then we're off to the races!

**Comment by iteles** [comment]
It was quick, I sorted it 👍

**Comment by RobStallion** [comment]
Thanks 👍

**Pull request merged**
